from sqlalchemy.orm import Session
import models, schemas

def get_employees(db:Session):
    return db.query(models.Employee).all()


def get_specific_employee(db:Session, emp_id: int):
    return ( db
            .query(models.Employee)
            .filter(models.Employee.id == emp_id)
            .first()
    )

def create_employee(db:Session, employee:schemas.EmployeeCreate):
    new_employee = models.Employee(
        name = employee.name,    # model requires two thing name and email id is autogenerated so in model.Employee, i passed name and email
        email = employee.email   # which than equals to employee. name which is of type str and email of type emailstr in schemas 
    )
    db.add(new_employee)
    db.commit()
    db.refresh(new_employee)
    return new_employee








